Update pr-ai_app_7107c5d_env_53c8a57.yaml

diff --git a/.github/workflows/pr-ai_app_7107c5d_env_53c8a57.yaml b/.github/workflows/pr-ai_app_7107c5d_env_53c8a57.yaml
--- a/.github/workflows/pr-ai_app_7107c5d_env_53c8a57.yaml
+++ b/.github/workflows/pr-ai_app_7107c5d_env_53c8a57.yaml
@@ -113,12 +113,18 @@ jobs:
 
                   echo "Starting Task"
                   response=$(curl -X POST -d "$payload"  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-auth-by: sa' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'Content-Type: application/json'  '${{ env.AI_SUGGESTED_SOLUTION_EP }}/fix-errors/')
-                  echo "Task Started Response: $response"
                   
                   task_id=$(echo "$response" | jq -r '.task_id')
-                  echo "Task ID: $task_id"
+                  
+                  if [-n "$task_id"]; then
+                    echo "Task Started Response: $response"
+                    echo "Task ID: $task_id"
+                  else
+                    echo "Task Id not found"
+                    exit 1
+                  fi
 
-                  while [ -z "$task_id" ]; do
+                  while [ -n "$task_id" ]; do
                     final_response=$(curl -X GET -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-auth-by: sa' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'Content-Type: application/json'  '${{ env.AI_SUGGESTED_SOLUTION_EP }}/fix-errors/$task_id')
 
                     task_status=$(echo "$final_response" | jq -r '.status')
